name: llmos-release

concurrency:
  group: main-release
  cancel-in-progress: true

on:
  push:
    branches:
      - llmos*

permissions:
  contents: write
  packages: write

env:
  REGISTRY: ${{ vars.REGISTRY || 'ghcr.io/llmos-ai' }}
  VERSION: ${{ github.ref_name }}

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: 1.21
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3
      - name: Set up Docker Buildx
        id: buildx
        uses: docker/setup-buildx-action@v3
        with:
          buildkitd-flags: --debug
      - name: Login to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Run GoReleaser
        uses: goreleaser/goreleaser-action@v5
        with:
          distribution: goreleaser
          version: latest
          args: release --clean --snapshot
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - name: Push Docker Images
        run: |
          IMAGES=$(docker images --format "{{.Repository}}:{{.Tag}}" | grep elemental-toolkit:${{ env.VERSION }})
          for i in ${IMAGES}; do
          docker push $i
          done
          docker manifest create ${{ env.REGISTRY }}/elemental-toolkit:${{ env.VERSION }} ${IMAGES}
          docker manifest push ${{ env.REGISTRY }}/elemental-toolkit:${{ env.VERSION }}
