name: test

on:
  pull_request:
    branches:
      - llmos*

env:
  REGISTRY: ${{ vars.REGISTRY || 'ghcr.io/llmos-ai' }}

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: 1.21
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3
      - name: Set up Docker Buildx
        id: buildx
        uses: docker/setup-buildx-action@v3
        with:
          buildkitd-flags: --debug
      - name: Get ref_name
        id: get_ref_name
        run: |
          if [ "${{ github.event_name }}" == "pull_request" ]; then
          echo "ref_name=${{ github.base_ref }}"
          echo "ref_name=${{ github.base_ref }}" >> $GITHUB_OUTPUT || exit 1
          else
          echo "ref_name=${{ github.ref_name }}"
          echo "ref_name=${{ github.ref_name }}" >> $GITHUB_OUTPUT || exit 1
          fi
      - name: Run GoReleaser
        uses: goreleaser/goreleaser-action@v5
        with:
          distribution: goreleaser
          version: latest
          args: release --clean --snapshot
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          VERSION: ${{ steps.get_ref_name.outputs.ref_name }}
